### ISSUE TITLE
Adding props for wapper children

### ISSUE THREAD

**Issue by ducnguyen4301** [alantoa/react-native-lightbox#4]
<img width="519" alt="Screen Shot 2023-06-25 at 10 21 17" src="https://github.com/alantoa/react-native-lightbox/assets/80993895/0fe719b0-02d9-4f74-9b0a-5af0a669c9e6">

Hi @alantoa , you need add JSX.Element[] in children for mutiple wapper children
**like this**
<img width="448" alt="Screen Shot 2023-06-25 at 10 22 27" src="https://github.com/alantoa/react-native-lightbox/assets/80993895/1ac39a2c-4eeb-4912-9d42-df5a7165376d">

**Comment by alantoa** [comment]
I just released v0.3.0 for your PR, thanks again!
